FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 80

# Run your service using uvicorn (if using FastAPI)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]

#CMD ["python", "main.py"]
